apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rpdu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rpdu
    app.kubernetes.io/part-of: test-app-moaz
  name: test-component-rpdu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-rpdu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-rpdu
    spec:
      containers:
      - image: quay.io/susdas/test-images:0fde717a19394dffb9e9aa71e2add1b4
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
