apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rpdu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rpdu
    app.kubernetes.io/part-of: test-app-moaz
  name: test-component-rpdu
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-rpdu
status:
  loadBalancer: {}
